version: '2'
services:
  proposal-app:
    image: proposal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proposal-postgresql:5432/proposal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://proposal-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://proposal-elasticsearch:9200
    ports:
      - 80:8080
  proposal-postgresql:
    extends:
      file: postgresql.yml
      service: proposal-postgresql
  proposal-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: proposal-elasticsearch
